# Generated by Django 5.1.6 on 2025-02-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_order',
            old_name='ordenando_por',
            new_name='ordenado_por',
        ),
    ]
